services:
  postgres-db:
    image: postgres:16-alpine
    container_name: local_postgres
    environment:
      POSTGRES_USER: sql_user
      POSTGRES_PASSWORD: MySecurePassword123
      POSTGRES_DB: analytics_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - C:/Users/pkumar/Documents/SQL-for-BI/data:/data

volumes:
  postgres_data: